app/modules/community/models.py
from app import db


# tabla intermedia para asociación comunidad con usuaario y evitar asocuiaciones Many2Many
community_members = db.Table('community_members',
                             db.Column('community_id', db.Integer, db.ForeignKey('community.id'), primary_key=True),
                             db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True)
                             )


class Community(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    description = db.Column(db.Text, nullable=False)
    owner_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    owner = db.relationship("User", back_populates="owned_communities", lazy=True)
    members = db.relationship(
        'User',
        secondary=community_members,
        back_populates='joined_communities'
    )

    datasets = db.relationship('DataSet', backref='community_datasets', lazy=True)

app/modules/community/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class CommunityForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(max=256)])
    description = TextAreaField('Description', validators=[DataRequired()])
    submit = SubmitField('Save community')

app/modules/community/__init__.py
from core.blueprints.base_blueprint import BaseBlueprint

community_bp = BaseBlueprint('community', __name__, template_folder='templates')

app/modules/community/routes.py
from flask import render_template, flash, jsonify, redirect, url_for
from app.modules.community import community_bp  # Ensure community_bp is imported
from flask_login import current_user, login_required
from app.modules.community.forms import CommunityForm
from app.modules.community.models import Community
from app.modules.community.services import CommunityService
from app.modules.dataset.models import DataSet
from app.modules.dataset.services import DataSetService
from app import db

community_service = CommunityService()
dataset_service = DataSetService()


@community_bp.route('/community', methods=['GET'])
def index():
    """List all communities for the current user."""
    all_communities = community_service.get_all()
    sorted_communities = []

    if current_user.is_authenticated:
        # Organize communities based on user ownership and membership
        owner_communities = [
            c for c in all_communities if c.owner_id == current_user.id
        ]
        member_communities = [
            c for c in all_communities if c.owner_id != current_user.id and current_user in c.members
        ]
        other_communities = [
            c for c in all_communities if c.owner_id != current_user.id and current_user not in c.members
        ]

        # Combine lists for display
        sorted_communities = (
            owner_communities + member_communities + other_communities
        )
    else:
        # Display all communities for unauthenticated users
        sorted_communities = all_communities

    return render_template('index.html', communities=sorted_communities)


@community_bp.route('/community/create', methods=['GET', 'POST'])
@login_required
def add_community():
    """Create a new community."""
    form = CommunityForm()
    if form.validate_on_submit():
        result = community_service.create(
            name=form.name.data,
            description=form.description.data,
            owner_id=current_user.id
        )
        return community_service.handle_service_response(
            result=result,
            errors=form.errors,
            success_url_redirect='community.index',
            success_msg='Community created successfully!',
            error_template='community/create.html',
            form=form
        )
    return render_template('create.html', form=form)


@community_bp.route('/community/delete/<int:community_id>', methods=['POST'])
@login_required
def remove_community(community_id):
    """Delete a community."""
    community = community_service.get_or_404(community_id)

    # Ensure the user is the owner before deletion
    if community.owner_id != current_user.id:
        flash("You are not authorized to delete this community.", "danger")
        return redirect(url_for('community.list_communities'))

    # Clear member relationships and delete the community
    community.members.clear()
    db.session.commit()
    db.session.delete(community)
    db.session.commit()
    flash("Community deleted successfully.", "success")
    return redirect(url_for('community.list_communities'))


@community_bp.route('/community/edit/<int:community_id>', methods=['GET', 'POST'])
@login_required
def update_community(community_id):
    """Update an existing community."""
    community = community_service.get_or_404(community_id)
    if community.owner_id != current_user.id:
        flash('You are not authorized to edit this community', 'error')
        return redirect(url_for('community.index'))

    form = CommunityForm(obj=community)
    if form.validate_on_submit():
        result = community_service.update(
            community_id,
            name=form.name.data,
            description=form.description.data
        )
        return community_service.handle_service_response(
            result=result,
            errors=form.errors,
            success_url_redirect='community.index',
            success_msg='Community updated successfully!',
            error_template='community/edit.html',
            form=form
        )
    return render_template('edit.html', form=form, community=community)


@community_bp.route('/community/<int:community_id>', methods=['GET'])
def view_community(community_id):
    """View a specific community."""
    community = community_service.get_or_404(community_id)
    user_id = current_user.id
    user_dataset = dataset_service.get_synchronized(user_id)
    datasets = community.datasets
    return render_template('show.html', community=community, datasets=datasets, user_dataset=user_dataset)


@community_bp.route('/community/join/<int:community_id>', methods=['POST'])
@login_required
def join_community(community_id):
    """Join a community."""
    community = Community.query.get(community_id)
    if not community:
        return jsonify({'error': 'Community not found'}), 404

    if community.owner_id == current_user.id:
        return jsonify({'error': 'You are the owner of this community'}), 403

    if current_user in community.members:
        return jsonify({'error': 'You are already a member of this community'}), 403

    community.members.append(current_user)
    db.session.commit()
    return redirect(url_for('community.index'))


@community_bp.route('/community/leave/<int:community_id>', methods=['POST'])
@login_required
def leave_community(community_id):
    """Join a community."""
    community = Community.query.get(community_id)
    if not community:
        return jsonify({'error': 'Community not found'}), 404

    if community.owner_id == current_user.id:
        return jsonify({'error': 'You are the owner of this community'}), 403

    if not (current_user in community.members):
        return jsonify({'error': 'You are not a member of this community'}), 403

    community.members.remove(current_user)
    db.session.commit()
    return redirect(url_for('community.index'))


@community_bp.route('/community/<int:community_id>/add_dataset/<int:dataset_id>', methods=['POST'])
@login_required
def add_dataset_to_community(community_id, dataset_id):
    """Add a dataset to a specific community."""
    dataset = DataSet.query.get(dataset_id)
    if not dataset:
        return jsonify({'error': 'Dataset is required'}), 400

    community = Community.query.get(community_id)
    if not community:
        return jsonify({'error': 'Community not found'}), 404

    # Assuming community has a method to add datasets
    community.datasets.append(dataset)  # This assumes dataset is an object that can be appended
    db.session.commit()

    return redirect(url_for('community.index'))


@community_bp.route('/community/<int:community_id>', methods=['POST'])
@login_required
def delete_community(community_id):
    """Leave a community."""
    community = community_service.get_or_404(community_id)
    if community.owner_id != current_user.id:
        flash('You are not authorized to delete this community', 'error')
        return redirect(url_for('community.index'))

    result = community_service.delete(community_id)
    if result:
        flash('Community deleted successfully!', 'success')
    else:
        flash('Error deleting community', 'error')

    return redirect(url_for('community.index'))

app/modules/community/templates/create.html
{% extends "base_template.html" %}

{% block title %}Create a New Community{% endblock %}

{% block content %}

<form method="POST" action="{{ url_for('community.add_community') }}">
    {{ form.hidden_tag() }}
    <div>
        {{ form.name.label }}<br>
        {{ form.name(size=32) }}
    </div>
    <div>
        {{ form.description.label }}<br>
        {{ form.description(rows=5) }}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('community.scripts') }}"></script>
{% endblock %}

app/modules/community/templates/edit.html
{% extends "base_template.html" %}

{% block title %}Edit Community{% endblock %}

{% block content %}

<form method="POST" action="{{ url_for('community.update_community', community_id=community.id) }}">
    {{ form.hidden_tag() }}
    <div>
        {{ form.name.label }}<br>
        {{ form.name(size=32, placeholder='Update community name') }}
        <small class="text-muted">* The community name must be unique.</small>
    </div>
    <div>
        {{ form.description.label }}<br>
        {{ form.description(rows=5, placeholder='Update community description') }}
    </div>
    <div>
        {{ form.submit(value='Save Changes') }}
    </div>
</form>

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('community.scripts') }}"></script>
{% endblock %}

app/modules/community/templates/index.html
{% extends "base_template.html" %}

{% block title %}Community List{% endblock %}

{% block content %}
<div>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('community.add_community') }}" class="btn btn-primary mb-4">Create a Community</a>
    {% endif %}
</div>

{% if communities %}
    <div class="row">
        {% for community in communities %}
        <div class="col-12 col-md-4 mb-4">
            <a class="text-decoration-none">
                <div class="card h-100 shadow-sm border-light">
                    <div class="card-body">
                        <h5 class="card-title">{{ community.name }}</h5>
                        <p class="card-text">{{ community.description }}</p>
                    </div>
                    {% if current_user.is_authenticated %}
                    {% if community.owner_id == current_user.id %}
                    <div class="card-footer text-end">
                        <form action="{{ url_for('community.delete_community', community_id=community.id) }}" method="POST" style="display:inline;">
                            <button type="submit" class="btn btn-danger btn-sm">Delete Community</button>
                        </form>
                        <form action="{{ url_for('community.update_community', community_id=community.id) }}" method="POST" style="display:inline;">
                            <button type="submit" class="btn btn-warning btn-sm">Edit Community</button>
                        </form>
                        <a href="{{ url_for('community.view_community', community_id=community.id) }}">
                            <i data-feather="eye"></i>
                        </a>
                    </div>
                    {% endif %}
                    {% if community.owner_id != current_user.id and current_user not in community.members %}
                    <div class="card-footer text-end">
                        <form action="{{ url_for('community.join_community', community_id=community.id) }}" method="POST" style="display:inline;">
                            <button type="submit" class="btn btn-primary btn-sm">Join Community</button>
                        </form>
                    </div>
                    {% endif %}
                    {% if community.owner_id != current_user.id and current_user in community.members %}
                    <div class="card-footer text-end">
                        <form action="{{ url_for('community.leave_community', community_id=community.id) }}" method="POST" style="display:inline;">
                            <button type="submit" class="btn btn-danger btn-sm">Leave Community</button>
                        </form>
                        <a href="{{ url_for('community.view_community', community_id=community.id) }}">
                            <i data-feather="eye"></i>
                        </a>
                    </div>
                    {% endif %}
                    {% endif %}
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
{% else %}
<p class="text-center" style="font-size: 1.5em;">
    You currently have no communities listed.
</p>
{% endif %}

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('community.scripts') }}"></script>
{% endblock %}

app/modules/community/templates/show.html
{% extends "base_template.html" %}

{% block title %}Community Information{% endblock %}

{% block content %}

<h1>{{ community.name }}</h1>
<p>{{ community.description }}</p>
<a href="{{ url_for('community.index') }}">Go Back to Community List</a>
{% for dataset in datasets %}
    <div class="card">
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between">
                <h2>
                    <a href="{{ dataset.get_uvlhub_doi() }}">
                        {{ dataset.ds_meta_data.title }}
                    </a>
                </h2>
                <div>
                    <span class="badge bg-secondary">{{ dataset.get_cleaned_publication_type() }}</span>
                </div>
            </div>
            <p class="text-secondary">{{ dataset.created_at.strftime('%B %d, %Y at %I:%M %p') }}</p>

            <div class="row mb-2">
                <div class="col-12">
                    <p class="card-text">{{ dataset.ds_meta_data.description }}</p>
                </div>
            </div>

            <div class="row mb-2 mt-4">
                <div class="col-12">
                    {% for author in dataset.ds_meta_data.authors %}
                        <p class="p-0 m-0">
                            {{ author.name }}
                            {% if author.affiliation %}
                                ({{ author.affiliation }})
                            {% endif %}
                            {% if author.orcid %}
                                ({{ author.orcid }})
                            {% endif %}
                        </p>
                    {% endfor %}
                </div>
            </div>

            <div class="row mb-2">
                <div class="col-12">
                    <a href="{{ dataset.get_uvlhub_doi() }}">{{ dataset.get_uvlhub_doi() }}</a>
                    <div id="dataset_doi_uvlhub_{{ dataset.id }}" style="display: none">
                        {{ dataset.get_uvlhub_doi() }}
                    </div>
                    <i data-feather="clipboard" class="center-button-icon"
                       style="cursor: pointer"
                       onclick="copyText('dataset_doi_uvlhub_{{ dataset.id }}')"></i>
                </div>
            </div>

            <div class="row mb-2">
                <div class="col-12">
                    {% for tag in dataset.ds_meta_data.tags.split(',') %}
                        <span class="badge bg-secondary">{{ tag.strip() }}</span>
                    {% endfor %}
                </div>
            </div>

            <div class="row mt-4">
                <div class="col-12">
                    <a href="{{ dataset.get_uvlhub_doi() }}" class="btn btn-outline-primary btn-sm"
                       style="border-radius: 5px;">
                        <i data-feather="eye" class="center-button-icon"></i>
                        View Dataset
                    </a>
                    <a href="/dataset/download/{{ dataset.id }}" class="btn btn-outline-primary btn-sm"
                       style="border-radius: 5px;">
                        <i data-feather="download" class="center-button-icon"></i>
                        Download ({{ dataset.get_file_total_size_for_human() }})
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
<p> Not shared datasets </p>
{% for dataset in user_dataset %}
{% if dataset not in datasets %}
    <div class="card">
        <div class="card-body">
            {{ dataset.ds_meta_data.title }}
        </div>
        <div class="card-footer text-end">
            <form action="{{ url_for('community.add_dataset_to_community', community_id=community.id, dataset_id=dataset.id) }}" method="POST" style="display:inline;">
                <button type="submit" class="btn btn-warning btn-sm">Add Community</button>
            </form>
        </div>
    <div>
{%endif%}
{% endfor %}
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('community.scripts') }}"></script>
{% endblock %}